### ISSUE TITLE
Mqtt branch!

### ISSUE THREAD

**Issue by JLFN** [torrottum/ikea-ansluta-esphome#10]
Hey,
Can you please make a MQTT branch that has the dimmer funktion?
Mqtt is universal and lets you use alot of other program then homeassistant.
There alot of benefits to keep mqtt .
Thank you in advance.

**Comment by torrottum** [comment]
It's still possible to use MQTT, but you need to [configure it in your ESPHome project](https://esphome.io/components/mqtt.html). That's one of the good things with the new custom component, you have more freedom on how you want to use it.

## Examples
Here's an example configuration that uses only MQTT without any dependency on HA (no api component defined):
```yaml
esphome:
  name: ikea_ansluta_using_mqtt
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Ikea Ansluta Fallback Hotspot"
    password: !secret ap_password

captive_portal:

logger:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

ota:

spi:
  clk_pin: GPIO14
  miso_pin: GPIO12
  mosi_pin: GPIO13

ikea_ansluta:
  cs_pin: GPIO15

light:
  - platform: ikea_ansluta
    name: 'My Light'
    remote_address: 0x35c0
  - platform: ikea_ansluta
    name: 'My Light 2'
    remote_address: 0xfefe
```

And example using MQTT and MQTT auto-discovery in HA (no api component here either):
```yaml
esphome:
  name: ikea_ansluta_using_mqtt
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Ikea Ansluta Fallback Hotspot"
    password: !secret ap_password

captive_portal:

logger:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

ota:

spi:
  clk_pin: GPIO14
  miso_pin: GPIO12
  mosi_pin: GPIO13

ikea_ansluta:
  cs_pin: GPIO15

light:
  - platform: ikea_ansluta
    name: 'My Light'
    remote_address: 0x35c0
  - platform: ikea_ansluta
    name: 'My Light 2'
    remote_address: 0xfefe
```


And here's an example using both MQTT and the HA API (but without auto discovery on MQTT, or else you will end up with multiple entities if you use the esphome integration):
```yaml
esphome:
  name: ikea_ansluta_using_mqtt
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Ikea Ansluta Fallback Hotspot"
    password: !secret ap_password

captive_portal:

logger:

api:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

ota:

spi:
  clk_pin: GPIO14
  miso_pin: GPIO12
  mosi_pin: GPIO13

ikea_ansluta:
  cs_pin: GPIO15

light:
  - platform: ikea_ansluta
    name: 'My Light'
    remote_address: 0x35c0
  - platform: ikea_ansluta
    name: 'My Light 2'
    remote_address: 0xfefe
```


The topics for these examples will be (Using only the first light here as an example):
- State topic: `ikea_ansluta_using_mqtt/light/my_light/state`
- Command topic: `ikea_ansluta_using_mqtt/light/my_light/command`

Example JSON payload to set the state: `{"state": "ON", "brightness": 128}` (if brightness <= 128 the light will be set to 50%, if brightness > 128 then 100%)

Hope this is helpful
